### ISSUE TITLE
Black Mesa Moon problem

### ISSUE THREAD

**Issue by ghost** [ImpulsiveLad/CentralConfig#2]
With this mod installed, the black mesa interior does not work on at least the black mesa moon (all other moons I have set the black mesa interior odds to very low so haven't tested with those but probably the same problem). It continuously causes the interior to scale lower and lower and lower until it hits 0 and then fails.

**Comment by ImpulsiveLass** [comment]
On the most recent build?

**Comment by ghost** [comment]
yes

**Comment by ImpulsiveLass** [comment]
:pensive:

Still trying to figure out what some specific interiors have this issue why 90% are just fine. Haven't found the connection.

**Comment by ghost** [comment]
> 😔
> 
> Still trying to figure out what some specific interiors have this issue why 90% are just fine. Haven't found the connection.

Well black mesa has its own tile size multiplier and when it was happening your mod would do the thing in your "miscellaneous fixes" where it reduces the size multiplier after each try but it was reducing it 30 times a second. I haven't looked at your code at all but I feel like there's a good chance something with the interior mods personal generation might be causing it to continuously false flag a dungeon generation failure every hundredth of a second to the point where it doesn't give the game a chance to even try starting the generation. I'm sure you already have but if not you should definitely test it out without that dungeon size reducing feature and see if the problem persists. Also maybe try overriding black mesas multiplier with LLL and see what happens. Idk shit but its worth a shot

**Comment by ImpulsiveLass** [comment]
Thats not it but your first line is intriguing.

I am recalling and relooping the generation process with different sizes after x failures. This works perfectly fine on the mass majority of interiors. The assumption would be that every interior must generate at *a* size so therefore trying out every reasonable size for generation over ~20 seconds will theoretically always find a successful generation.
However black mesa, the bunker, the tomb, and the scp dungeon to name some I know of will fail to generate a few hundred times and I don't understand why.

It is most likely due to some complexity in how it is using DunGen. the size difference shouldn't matter so much as the size handling of mine is done directly through DunGen which takes the lengthmultiplier as a target to generate off of. Other than rewriting the failure loop I am not changing anything else with it. The dungeon selection, setting, and initial clamping are either done through LLL functions or basic C# math

![Screenshot 2024-07-21 230918](https://github.com/user-attachments/assets/c4b38dbf-dc96-4a20-baa5-818f67d4ad62)

This is the bulk of what I am changing about DunGen, this is ran in place of the isretry loop of innergenerate

![Screenshot 2024-07-21 231003](https://github.com/user-attachments/assets/35e3c0c9-4889-4e73-a0d4-2a26a88ec0b9)

**Comment by SpazzMaticus107** [comment]
I'm getting the same issue sadly :<

**Comment by ImpulsiveLass** [comment]
Fixed by 45460340d9aed24f95362dd76ec9a4c03094fb24

**Comment by ghost** [comment]
Thank you for fixing. I am curious, what was the problem?

**Comment by ImpulsiveLass** [comment]
Loadstone enabled Dungen‘s GenerateAsyncronously setting which allows the process to skip frames. (Basically fake multithreading). So the exception I throw cannot catch since more then one process is running.
